server:
  port: 8769
spring:
  application:
    name: admin-server
  security:
    user:
      name: admin
      password: Pa$$w0rd
  mail:
    host: smtp3.hp.com
    port:
  boot:
    admin:
      ui:
        title: Service Monitoring
        favicon: img/favicon.ico
        brand: <img src='img/favicon.ico'><span>Service Monitoring</span>
      notify:
        mail:
          from: xiaodong.liu@hp.com
          to: xiaodong.liu@hp.com